### PR TITLE
Handle managment of signal simpler

### PR DESCRIPTION
**Pull request by lyrixx**
1. I did not test it
2. As you don't require ext pcntl in you composer.json you should check if functions are available
3. As you declare `ticks =1` and you exit when signaled, this code is useless.

My 2 cents ;)

### CODE REVIEW

**Comment by gnugat** [comment]
Hey! Thanks for your contribution :) .
It looks like your attempt doesn't work. It might be because exit is a keyword (the same goes for `empty`).

But you've got a point: I didn't know `pcntl_signal` was part of an external library, I'll add it in the requirements.

`tick` is there because I'm using an infinite loop with a sleep in it, if it wasn't there I'd have to hit `Control-C` right before the wait statement. This can be easily removed by replacing this loop with a select ;) .

**Comment by lyrixx** [comment]
instead of exit, use die. I think it woks.

About the tick, as you do nothing than exit, the signal managment is useless, right ?
And, a select is useless here too.

usually, we use signal like that 

``` php

<?php

class FooBar implements DaemonInterface
{
    private $stopped;

    public function __construct()
    {
        $this->stopped = false;
    }

    public function run()
    {
        while (true) {
            pcntl_signal_dispatch();

            if ($this->stopped) {
                return;
            }

            // do you job

            usleep(200000);
        }

    }

    public function stop()
    {
        $this->stopped = true;
    }

}

// in the main entry point

$deamon = new Foobar();

pcntl_signal(SIGTERM, function () use ($daemon) {
    $daemon->stop();
});
pcntl_signal(SIGINT, function () use ($daemon) {
    $daemon->stop();
});

$daemon->run();

```

BTW, I planned to blog about that.

**Comment by lyrixx** [comment]
Anyway, If you are at sensiolabs tomorrow, I could explain this ;)

**Comment by gnugat** [comment]
I'd be glad to both read and hear about it, thanks.

**Pull request closed without merging**
